### ISSUE TITLE
Very good repo, but i kbd.

### ISSUE THREAD

**Issue by Holit** [MadLongTom/Prolegomenon#1]
# Very good repo, but i kbd
⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨⑨
-------------
[只有聪明人才能看到的链接](https://music.163.com/#/song?id=22636718)
琪露诺的主题曲。
果然，作成了有些笨的少女的印象。
也因为这样变成了不知道是明快还是阴暗的曲子也没什么关系。
高速宁静的主旋律之类的。
算了，反正是第二关（哦

**Comment by MadLongTom** [comment]
Very good issue, but you are quite dinner. :>
